# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3749551ee0056e705a638d76eb0745161d5c35d33d208f733174e2d8600d755e3f17c5ee84179eefbb29142e5c8e90bfebcdd63d89f67c965a0b0eb75a01cdfb

test:
  secret_key_base: a1beeb4429fd72d57c74b2bbf001419241df825587ff41b23e5aef617650fe1a455fdf431de988b03a2bef29d16b66f5b82f0600356edfe7e2a35b4bf4badc75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
